# This is a basic workflow to help you get started with Actions

name: github action


on:
  pull_request:
    branches: 
      - master
    paths:
      - 'conf/**'

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
  push:
    branches: 
      - master
    paths:
      - 'conf/**'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  pull-request-check:
    # if: github.event_name == 'pull_request'
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2

    - name: Run check 
      run: |
          echo "check"
  # This workflow contains a single job called "build"
  merge-branch:
    if: github.event_name == 'push'
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Run push
      run: |
          echo "push"

    # Runs a set of commands using the runners shell
    # - name: Run a multi-line script
    #   run: |
    #     sudo bash -x scripts/install.sh
    
    # Runs a set of commands using the ssh
    # - name: test ssh command
    #   uses: appleboy/ssh-action@master
    #   with:
    #     host: ${{ secrets.ghost_host }}
    #     username: ${{ secrets.ghost_user }}
    #     key: ${{ secrets.github_private_key }}
    #     port: ${{ secrets.ghost_port }}
    #     script: |
    #       whoami
    #       ls -al

    # - name: test scp command
    #   uses: AEnterprise/rsync-deploy@v1.0
    #   env:
    #     DEPLOY_KEY: ${{ secrets.github_private_key }}
    #     ARGS: "-e -c -r --delete"
    #     SERVER_PORT: ${{ secrets.ghost_port }}
    #     FOLDER: ""
    #     SERVER_IP: ${{ secrets.ghost_host }}
    #     USERNAME: ${{ secrets.ghost_user }}
    #     SERVER_DESTINATION: "/tmp"

    # - name: rsync deployments
    #   uses: burnett01/rsync-deployments@4.0
    #   with:
    #     switches: -avzr --delete
    #     path: /
    #     remote_path: /tmp/
    #     remote_host: ${{ secrets.ghost_host }}
    #     remote_port: ${{ secrets.ghost_port }}
    #     remote_user: ${{ secrets.ghost_user }}
    #     remote_key: ${{ secrets.github_private_key }}
